// client-vue/src/features/workflow-editor/components/settings/editors/CodeEditor.vue
<template>
  <div class="editor-stack">
    <EditorField label="Step Name">
      <input
        class="editor-input editor-input--bold"
        :value="node.data.name || ''"
        @input="updateNodeData({ name: ($event.target as HTMLInputElement).value })"
        placeholder="Name this code block"
      />
    </EditorField>

    <EditorField label="JavaScript Code" icon="code-2">
      <div class="editor-hint editor-hint--amber">
        Available:
        <span class="editor-code-snippet">context.trigger</span>,
        <span class="editor-code-snippet">context.steps</span>,
        <span class="editor-code-snippet">variables</span>
      </div>
      <textarea
        class="editor-textarea"
        :value="node.data.script || ''"
        @input="updateNodeData({ script: ($event.target as HTMLTextAreaElement).value })"
        placeholder="// Access context and variables\nconst items = context.steps.prevStep.output;\nconst result = items.filter(i => i.active);\nreturn result;"
        spellcheck="false"
      />
    </EditorField>
  </div>
</template>

<script setup lang="ts">
import type { NodeEditorProps } from './types'
import EditorField from './EditorField.vue'

defineProps<NodeEditorProps>()
</script>

<style scoped>

</style>

// client/app/modules/forge/workflows/components/node-editors/CodeEditor.tsx
import { Input } from "~/components/ui/input";
import { Code2 } from "lucide-react";
import type { CodeNode } from "../../types/workflow-types";
import type { NodeEditorProps } from "./types";

export function CodeEditor({ node, updateNodeData }: NodeEditorProps) {
  const data = node.data as unknown as CodeNode;

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-2">
        <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">
          Step Name
        </label>
        <Input
          value={data.name || ""}
          onChange={(e) => updateNodeData({ name: e.target.value })}
          placeholder="Name this code block"
          className="bg-accent/10 border-border/50 h-10 font-bold"
        />
      </div>

      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-2 mb-1">
          <Code2 className="w-3.5 h-3.5 text-amber-500" />
          <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
            JavaScript Code
          </label>
        </div>
        <div className="flex items-center gap-2 p-2 text-[10px] bg-amber-500/5 border border-amber-500/10 rounded-lg text-amber-500">
          <span className="font-bold">
            Available: <code className="text-[9px]">context.trigger</code>,{" "}
            <code className="text-[9px]">context.steps</code>,{" "}
            <code className="text-[9px]">variables</code>
          </span>
        </div>
        <textarea
          value={data.script || ""}
          onChange={(e) => updateNodeData({ script: e.target.value })}
          placeholder={`// Access context and variables\nconst items = context.steps.prevStep.output;\nconst result = items.filter(i => i.active);\nreturn result;`}
          className="flex min-h-[200px] w-full rounded-lg border border-border/50 bg-background px-3 py-3 text-xs font-mono ring-offset-background placeholder:text-muted-foreground/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 resize-y leading-relaxed"
          spellCheck={false}
        />
      </div>
    </div>
  );
}
