// client/app/modules/forge/workflows/components/node-editors/PluginEditor.tsx
import { useState } from "react";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { Switch } from "~/components/ui/switch";
import { Check, Search } from "lucide-react";
import type { PluginNode } from "../../types/workflow-types";
import type { NodeEditorProps } from "./types";
import { useForge } from "~/providers/ForgeProvider";
import {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
} from "~/components/ui/combobox";
import {
  resolveSchemaTree,
  resolveTriggerPaths,
  type SchemaPath,
} from "../../utils/schemaResolver";

// ──────────── Variable Tree ────────────

/**
 * A searchable variable tree that shows all injectable paths from all
 * upstream nodes and the trigger. Each path is a clickable chip that
 * appends `{{ path }}` to the target input.
 */
function VariableTree({
  paramKey,
  upstreamNodes,
  nodes,
  onInject,
}: {
  paramKey: string;
  upstreamNodes: NodeEditorProps["upstreamNodes"];
  nodes: NodeEditorProps["nodes"];
  onInject: (paramKey: string, path: string) => void;
}) {
  const { plugins } = useForge();
  const [search, setSearch] = useState("");

  // Collect all schema paths from all upstream nodes
  const allPaths: SchemaPath[] = [];

  for (const upNode of upstreamNodes) {
    if (upNode.id === "trigger") {
      const triggerData = upNode.data as any;
      const triggerPaths = resolveTriggerPaths(triggerData.schema);
      allPaths.push(...triggerPaths);
      // Also offer the whole trigger payload
      if (!triggerData.schema || Object.keys(triggerData.schema).length === 0) {
        allPaths.push({
          path: "trigger",
          label: "trigger.payload",
          type: "object",
          sourceNodeName: "Trigger",
        });
      }
      continue;
    }

    const upData = upNode.data as any;
    const nodeName: string = upData.name || upNode.id;

    if (!upData.pluginId) {
      // Non-plugin node: offer generic .output
      allPaths.push({
        path: `steps.${upNode.id}.output`,
        label: "output",
        type: "any",
        sourceNodeName: nodeName,
      });
      continue;
    }

    // Plugin node: resolve full schema tree
    const upPlugin = plugins.find((p) => p.id === upData.pluginId);
    const upMethod = upPlugin?.manifest.methods[upData.action];
    if (upMethod?.responseSchema) {
      const paths = resolveSchemaTree(upNode.id, nodeName, upMethod.responseSchema);
      allPaths.push(...paths);
    } else {
      allPaths.push({
        path: `steps.${upNode.id}.output`,
        label: "output",
        type: "any",
        sourceNodeName: nodeName,
      });
    }
  }

  const filtered = search
    ? allPaths.filter(
        (p) =>
          p.path.toLowerCase().includes(search.toLowerCase()) ||
          p.label.toLowerCase().includes(search.toLowerCase()) ||
          p.sourceNodeName.toLowerCase().includes(search.toLowerCase()),
      )
    : allPaths;

  if (allPaths.length === 0) return null;

  // Group by sourceNodeName
  const grouped = new Map<string, SchemaPath[]>();
  for (const p of filtered) {
    const group = grouped.get(p.sourceNodeName) ?? [];
    group.push(p);
    grouped.set(p.sourceNodeName, group);
  }

  return (
    <div className="flex flex-col gap-2 mt-1">
      {/* Search bar */}
      <div className="flex items-center gap-1.5 px-2 py-1.5 rounded-lg border border-border/50 bg-background">
        <Search className="w-3 h-3 text-muted-foreground shrink-0" />
        <input
          className="flex-1 bg-transparent text-[10px] outline-none placeholder:text-muted-foreground/50"
          placeholder="Search variables..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {/* Grouped chips */}
      {Array.from(grouped.entries()).map(([groupName, paths]) => (
        <div key={groupName} className="flex flex-col gap-1">
          <span className="text-[9px] uppercase font-black tracking-widest text-muted-foreground/60 ml-0.5">
            {groupName}
          </span>
          <div className="flex flex-wrap gap-1.5">
            {paths.map((p) => (
              <button
                key={p.path}
                className="bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-500 text-[10px] px-2.5 py-1.5 rounded-lg border border-emerald-500/20 transition-all active:scale-95 font-bold flex items-center gap-1 max-w-full"
                title={p.path}
                onClick={() => onInject(paramKey, p.path)}
              >
                <Check className="w-2.5 h-2.5 opacity-50 shrink-0" />
                <span className="truncate">{p.label}</span>
                <span className="opacity-40 text-[8px] shrink-0">{p.type}</span>
              </button>
            ))}
          </div>
        </div>
      ))}

      {filtered.length === 0 && (
        <p className="text-[10px] text-muted-foreground/50 italic px-1">
          No variables match "{search}"
        </p>
      )}
    </div>
  );
}

// ──────────── PluginEditor ────────────

export function PluginEditor({
  node,
  nodes,
  edges,
  updateNodeData,
  injectVariable,
  upstreamNodes,
}: NodeEditorProps) {
  const { plugins } = useForge();
  const data = node.data as unknown as PluginNode;
  const selectedPlugin = plugins.find((p) => p.id === data.pluginId);
  const selectedAction = selectedPlugin?.manifest.methods[data.action];

  return (
    <div className="flex flex-col gap-6">
      {/* Step name */}
      <div className="flex flex-col gap-2">
        <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">
          Step Name
        </label>
        <Input
          value={data.name || ""}
          onChange={(e) => updateNodeData({ name: e.target.value })}
          placeholder="What does this step do?"
          className="bg-accent/10 border-border/50 h-10 font-bold"
        />
      </div>

      {/* Plugin selector */}
      <div className="flex flex-col gap-2">
        <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">
          Integration (Plugin)
        </label>
        <Combobox
          value={data.pluginId || undefined}
          onValueChange={(val) =>
            updateNodeData({ pluginId: val || "", action: "", params: {} })
          }
        >
          <ComboboxInput
            className="w-full h-10 bg-accent/10 border-border/50 font-bold text-sm pointer-events-auto"
            placeholder="Select Integration..."
          />
          <ComboboxContent className="z-[100] pointer-events-auto">
            <ComboboxList>
              {plugins.map((p) => (
                <ComboboxItem
                  key={p.id}
                  value={p.id}
                  className="text-sm font-bold py-2 px-3 cursor-pointer"
                >
                  {p.manifest.metadata.name}
                </ComboboxItem>
              ))}
            </ComboboxList>
            <ComboboxEmpty>No integrations found.</ComboboxEmpty>
          </ComboboxContent>
        </Combobox>
      </div>

      {/* Action selector */}
      {selectedPlugin && (
        <div className="flex flex-col gap-2">
          <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">
            Action
          </label>
          <Combobox
            value={data.action || undefined}
            onValueChange={(val) =>
              updateNodeData({ action: val || "", params: {} })
            }
          >
            <ComboboxInput
              className="w-full h-10 bg-accent/10 border-border/50 font-bold text-sm pointer-events-auto"
              placeholder="Select Action..."
            />
            <ComboboxContent className="z-[100] pointer-events-auto">
              <ComboboxList>
                {Object.entries(selectedPlugin.manifest.methods || {}).map(
                  ([key, method]) => (
                    <ComboboxItem
                      key={key}
                      value={key}
                      className="text-sm font-bold py-2 px-3 cursor-pointer"
                    >
                      {method.metadata.label || key}
                    </ComboboxItem>
                  ),
                )}
              </ComboboxList>
              <ComboboxEmpty>No actions found.</ComboboxEmpty>
            </ComboboxContent>
          </Combobox>
        </div>
      )}

      {/* Parameters */}
      {selectedAction && (
        <div className="flex flex-col gap-5 mt-2">
          <div className="flex items-center gap-2 border-b border-border/50 pb-2">
            <div className="w-1.5 h-4 bg-primary rounded-full" />
            <h3 className="text-[11px] font-black text-foreground/70 uppercase tracking-widest">
              Parameters
            </h3>
          </div>

          {Object.entries(selectedAction.parameters?.properties || {}).map(
            ([paramKey, paramVal]) => {
              const isRequired = (
                selectedAction.parameters?.required ?? []
              ).includes(paramKey);

              return (
                <div
                  key={paramKey}
                  className="flex flex-col gap-3 p-4 rounded-xl bg-accent/5 border border-border/50"
                >
                  {/* Param header */}
                  <div className="flex justify-between items-start">
                    <div className="flex flex-col gap-0.5">
                      <span className="text-[10px] font-black uppercase tracking-widest text-foreground">
                        {(paramVal as any)["x-label"] || paramKey}
                      </span>
                      {(paramVal as any).description && (
                        <span className="text-[9px] text-muted-foreground leading-none mt-0.5">
                          {(paramVal as any).description}
                        </span>
                      )}
                      {isRequired && (
                        <span className="text-[9px] font-black uppercase text-destructive/80 leading-none mt-0.5">
                          Required field
                        </span>
                      )}
                    </div>
                    <span className="text-[10px] bg-accent/20 px-1.5 py-0.5 rounded text-muted-foreground uppercase font-black tracking-tighter border border-border/30">
                      {(paramVal as any).type}
                    </span>
                  </div>

                  {/* Enum → Combobox */}
                  {(paramVal as any).enum ? (
                    <Combobox
                      value={data.params?.[paramKey] || undefined}
                      onValueChange={(val) =>
                        updateNodeData({
                          params: { ...(data.params || {}), [paramKey]: val },
                        })
                      }
                    >
                      <ComboboxInput
                        className="w-full h-10 font-bold text-sm bg-background border-border/50 pointer-events-auto"
                        placeholder={`Select ${
                          (paramVal as any)["x-label"] || paramKey
                        }...`}
                      />
                      <ComboboxContent className="z-[100] pointer-events-auto">
                        <ComboboxList>
                          {((paramVal as any).enum as string[]).map((val) => (
                            <ComboboxItem
                              key={val}
                              value={val}
                              className="text-sm font-bold py-2 px-3 cursor-pointer"
                            >
                              {val}
                            </ComboboxItem>
                          ))}
                        </ComboboxList>
                      </ComboboxContent>
                    </Combobox>
                  ) : (paramVal as any)["x-input-type"] === "toggle" ||
                    (paramVal as any).type === "boolean" ? (
                    <div className="flex items-center gap-2 h-10">
                      <Switch
                        checked={!!data.params?.[paramKey]}
                        onCheckedChange={(val) =>
                          updateNodeData({
                            params: {
                              ...(data.params || {}),
                              [paramKey]: val,
                            },
                          })
                        }
                      />
                      <span className="text-xs text-muted-foreground italic font-medium">
                        {data.params?.[paramKey] ? "Enabled" : "Disabled"}
                      </span>
                    </div>
                  ) : (paramVal as any)["x-input-type"] === "textarea" ? (
                    <Textarea
                      className="font-bold text-sm bg-background border-border/50 min-h-24"
                      value={data.params?.[paramKey] || ""}
                      onChange={(e) =>
                        updateNodeData({
                          params: {
                            ...(data.params || {}),
                            [paramKey]: e.target.value,
                          },
                        })
                      }
                      placeholder={
                        (paramVal as any).description
                          ? `e.g. ${(paramVal as any).default ?? ""}`
                          : `Enter value for ${paramKey}`
                      }
                    />
                  ) : (
                    <Input
                      className="font-bold text-sm bg-background border-border/50 h-10"
                      value={data.params?.[paramKey] || ""}
                      onChange={(e) =>
                        updateNodeData({
                          params: {
                            ...(data.params || {}),
                            [paramKey]: e.target.value,
                          },
                        })
                      }
                      placeholder={
                        (paramVal as any).description
                          ? `e.g. ${(paramVal as any).default ?? ""}`
                          : `Enter value for ${paramKey}`
                      }
                    />
                  )}

                  {/* Variable tree — only shown when there are upstream nodes */}
                  {upstreamNodes.length > 0 && (
                    <div className="flex flex-col gap-1">
                      <span className="text-[10px] uppercase font-black tracking-widest text-muted-foreground flex items-center gap-1.5 opacity-60">
                        <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                        Map variables
                      </span>
                      <VariableTree
                        paramKey={paramKey}
                        upstreamNodes={upstreamNodes}
                        nodes={nodes}
                        onInject={injectVariable}
                      />
                    </div>
                  )}
                </div>
              );
            },
          )}
        </div>
      )}
    </div>
  );
}

// client-vue/src/features/workflow-editor/components/settings/editors/PluginEditor.vue
<template>
  <div class="editor-stack">
    <!-- Step name -->
    <EditorField label="Step Name">
      <input
        class="editor-input editor-input--bold"
        :value="data.name || ''"
        @input="updateNodeData({ name: ($event.target as HTMLInputElement).value })"
        placeholder="What does this step do?"
      />
    </EditorField>

    <!-- Plugin selector -->
    <EditorField label="Integration (Plugin)">
      <select
        class="editor-select"
        :value="data.pluginId || ''"
        @change="
          updateNodeData({
            pluginId: ($event.target as HTMLSelectElement).value,
            action: '',
            params: {},
          })
        "
      >
        <option value="" disabled>Select Integration...</option>
        <option v-for="p in plugins" :key="p.id" :value="p.id">
          {{ p.manifest.metadata.name }}
        </option>
      </select>
    </EditorField>

    <!-- Action selector -->
    <EditorField v-if="selectedPlugin" label="Action">
      <select
        class="editor-select"
        :value="data.action || ''"
        @change="updateNodeData({ action: ($event.target as HTMLSelectElement).value, params: {} })"
      >
        <option value="" disabled>Select Action...</option>
        <option
          v-for="(method, key) in selectedPlugin.manifest.methods || {}"
          :key="key"
          :value="key"
        >
          {{ method.metadata.label || key }}
        </option>
      </select>
    </EditorField>

    <!-- Parameters container -->
    <div v-if="selectedAction" class="editor-stack mt-2">
      <div class="pe-params-header">
        <div class="pe-params-indicator"></div>
        <h3 class="pe-params-title">Parameters</h3>
      </div>

      <div
        v-for="(paramVal, paramKey) in selectedAction.parameters?.properties || {}"
        :key="paramKey"
        class="pe-param-card"
      >
        <!-- Param header -->
        <div class="pe-param-head">
          <div class="pe-param-info">
            <span class="pe-param-label">{{ paramVal['x-label'] || paramKey }}</span>
            <span v-if="paramVal.description" class="pe-param-desc">{{
              paramVal.description
            }}</span>
            <span v-if="isRequired(paramKey.toString())" class="pe-param-req">Required field</span>
          </div>
          <span class="pe-param-type">{{ paramVal.type || 'any' }}</span>
        </div>

        <!-- Inputs mapping -->
        <!-- Enum -> Select -->
        <template v-if="(paramVal as any).enum">
          <select
            class="editor-select"
            :value="(data.params as any)?.[paramKey] || ''"
            @change="
              updateNodeData({
                params: {
                  ...(data.params || {}),
                  [paramKey]: ($event.target as HTMLSelectElement).value,
                },
              })
            "
          >
            <option value="" disabled>
              Select {{ (paramVal as any)['x-label'] || paramKey }}...
            </option>
            <option v-for="val in (paramVal as any).enum" :key="val" :value="val">{{ val }}</option>
          </select>
        </template>

        <!-- Boolean / Toggle -->
        <template
          v-else-if="
            (paramVal as any)['x-input-type'] === 'toggle' || (paramVal as any).type === 'boolean'
          "
        >
          <div class="pe-param-toggle">
            <BaseSwitch
              :model-value="!!data.params?.[paramKey]"
              @update:model-value="
                (val) => updateNodeData({
                  params: {
                    ...(data.params || {}),
                    [paramKey]: val,
                  },
                })
              "
            />
            <span class="pe-param-toggle-text">{{
              data.params?.[paramKey] ? 'Enabled' : 'Disabled'
            }}</span>
          </div>
        </template>

        <!-- Textarea -->
        <template v-else-if="(paramVal as any)['x-input-type'] === 'textarea'">
          <textarea
            class="editor-textarea"
            :value="(data.params as any)?.[paramKey] || ''"
            @input="
              updateNodeData({
                params: {
                  ...(data.params || {}),
                  [paramKey]: ($event.target as HTMLTextAreaElement).value,
                },
              })
            "
            :placeholder="
              (paramVal as any).description
                ? `e.g. ${(paramVal as any).default ?? ''}`
                : `Enter value for ${paramKey}`
            "
          />
        </template>

        <!-- Files Array Input -->
        <template v-else-if="(paramVal as any)['x-input-type'] === 'files'">
          <div class="pe-files-container">
            <div 
              v-for="(item, index) in (Array.isArray((data.params as any)?.[paramKey]) ? (data.params as any)?.[paramKey] : ((data.params as any)?.[paramKey] ? [(data.params as any)?.[paramKey]] : ['']))" 
              :key="index"
              class="pe-file-input-group"
            >
              <input
                class="editor-input editor-input--bold"
                :value="item"
                @input="updateFileArray(paramKey.toString(), index, ($event.target as HTMLInputElement).value)"
                placeholder="e.g. {{ trigger.file }}"
              />
              <button 
                class="pe-file-btn pe-file-btn--remove" 
                @click="removeFileFromArray(paramKey.toString(), index)"
                title="Remove file"
              >
                <LucideIcon name="trash" size="14" />
              </button>
            </div>
            <button class="pe-file-btn pe-file-btn--add" @click="addFileToArray(paramKey.toString())">
              <LucideIcon name="plus" size="14" />
              <span>Add File</span>
            </button>
          </div>
        </template>

        <!-- Default Input -->
        <template v-else>
          <input
            class="editor-input editor-input--bold"
            :value="(data.params as any)?.[paramKey] || ''"
            @input="
              updateNodeData({
                params: {
                  ...(data.params || {}),
                  [paramKey]: ($event.target as HTMLInputElement).value,
                },
              })
            "
            :placeholder="
              (paramVal as any).description
                ? `e.g. ${(paramVal as any).default ?? ''}`
                : `Enter value for ${paramKey}`
            "
          />
        </template>

        <!-- Variable map trigger & tree -->
        <div v-if="upstreamNodes.length > 0" class="pe-var-container">
          <div class="pe-var-divider">
            <div class="pe-var-line"></div>
            <button class="pe-var-btn" @click="toggleMapVariables(paramKey.toString())">
              <LucideIcon
                :name="isMapVariablesOpen(paramKey.toString()) ? 'chevron-up' : 'chevron-down'"
                size="12"
              />
              <span>Map variables</span>
            </button>
            <div class="pe-var-line"></div>
          </div>

          <VariableTree
            v-if="isMapVariablesOpen(paramKey.toString())"
            :param-key="paramKey.toString()"
            :upstream-nodes="upstreamNodes"
            :nodes="nodes"
            @inject="injectVariable"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { NodeEditorProps } from './types'
import { useApi } from '@/shared/composables/useApi'
import { pluginsApi } from '@/core/api/plugins.api'
import EditorField from './EditorField.vue'
import VariableTree from './VariableTree.vue'
import BaseSwitch from '@/shared/components/base/BaseSwitch.vue'
import LucideIcon from '@/shared/icons/LucideIcon.vue'
import type { PluginNode } from '@/core/types/workflow.types'

const props = defineProps<NodeEditorProps>()

const data = computed(() => props.node.data as unknown as PluginNode)

const { data: plugins, execute: executePlugins } = useApi(pluginsApi.getAll, [])
executePlugins()

const selectedPlugin = computed(() => {
  return plugins.value?.find((p) => p.id === data.value.pluginId)
})

const selectedAction = computed(() => {
  return selectedPlugin.value?.manifest.methods[data.value.action]
})

const isRequired = (key: string) => {
  return (selectedAction.value?.parameters?.required ?? []).includes(key)
}

const mapVariablesOpen = ref<Record<string, boolean>>({})

const isMapVariablesOpen = (key: string) => mapVariablesOpen.value[key] ?? false

const toggleMapVariables = (key: string) => {
  mapVariablesOpen.value[key] = !mapVariablesOpen.value[key]
}

const updateFileArray = (key: string, index: number, value: string) => {
  let currentArray = Array.isArray((data.value.params as any)?.[key]) 
    ? [...(data.value.params as any)[key]] 
    : ((data.value.params as any)?.[key] ? [(data.value.params as any)[key]] : [''])
  
  currentArray[index] = value
  
  updateNodeData({
    params: {
      ...(data.value.params || {}),
      [key]: currentArray,
    },
  })
}

const addFileToArray = (key: string) => {
  let currentArray = Array.isArray((data.value.params as any)?.[key]) 
    ? [...(data.value.params as any)[key]] 
    : ((data.value.params as any)?.[key] ? [(data.value.params as any)[key]] : [''])
    
  currentArray.push('')
  
  updateNodeData({
    params: {
      ...(data.value.params || {}),
      [key]: currentArray,
    },
  })
}

const removeFileFromArray = (key: string, index: number) => {
  let currentArray = Array.isArray((data.value.params as any)?.[key]) 
    ? [...(data.value.params as any)[key]] 
    : ((data.value.params as any)?.[key] ? [(data.value.params as any)[key]] : [''])
    
  currentArray.splice(index, 1)
  
  if (currentArray.length === 0) {
    currentArray.push('')
  }
  
  updateNodeData({
    params: {
      ...(data.value.params || {}),
      [key]: currentArray,
    },
  })
}
</script>

<style scoped>
.mt-2 {
  margin-top: var(--nod8-space-2);
}

.pe-params-header {
  display: flex;
  align-items: center;
  gap: var(--nod8-space-2);
  border-bottom: 1px solid var(--nod8-border);
  padding-bottom: var(--nod8-space-2);
}

.pe-params-indicator {
  width: 4px;
  height: 16px;
  background-color: var(--nod8-text-primary);
  border-radius: 9999px;
}

.pe-params-title {
  font-size: 11px;
  font-weight: 900;
  color: var(--nod8-text-primary);
  opacity: 0.7;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin: 0;
}

.pe-param-card {
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-3);
  padding: var(--nod8-space-4);
  border-radius: var(--nod8-radius-lg);
  border: 1px solid var(--nod8-border);
}

.pe-param-head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.pe-param-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.pe-param-label {
  font-size: 11px;
  font-weight: 900;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--nod8-text-primary);
}

.pe-param-desc {
  font-size: 10px;
  color: var(--nod8-text-muted);
  line-height: 1;
  margin-top: 2px;
}

.pe-param-req {
  font-size: 10px;
  font-weight: 900;
  text-transform: uppercase;
  color: rgba(239, 68, 68, 0.8);
  line-height: 1;
  margin-top: 2px;
}

.pe-param-type {
  font-size: 11px;
  padding: 2px 6px;
  border-radius: 4px;
  color: var(--nod8-text-muted);
  text-transform: uppercase;
  font-weight: 900;
  letter-spacing: -0.05em;
  border: 1px solid var(--nod8-border);
}

.pe-param-toggle {
  display: flex;
  align-items: center;
  gap: var(--nod8-space-2);
  height: 40px;
}

.pe-param-toggle-text {
  font-size: var(--nod8-text-xs);
  color: var(--nod8-text-muted);
  font-style: italic;
  font-weight: 500;
}


.pe-var-container {
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-1);
}

.pe-var-divider {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: var(--nod8-space-2);
}

.pe-var-line {
  flex: 1;
  height: 1px;
  background-color: var(--nod8-border);
}

.pe-var-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 4px 8px;
  border-radius: var(--nod8-radius-sm);
  font-size: 11px;
  color: var(--nod8-text-muted);
}

.pe-var-btn:hover {
  background-color: var(--nod8-bg-surface);
  color: var(--nod8-text-primary);
}

.pe-files-container {
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-2);
}

.pe-file-input-group {
  display: flex;
  gap: var(--nod8-space-2);
  align-items: center;
}

.pe-file-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--nod8-bg-surface);
  border: 1px solid var(--nod8-border);
  color: var(--nod8-text-muted);
  cursor: pointer;
  border-radius: var(--nod8-radius-sm);
  transition: all 0.2s ease;
}

.pe-file-btn:hover {
  color: var(--nod8-text-primary);
  background: var(--nod8-bg-surface-hover);
}

.pe-file-btn--remove {
  width: 36px;
  height: 36px;
  flex-shrink: 0;
}

.pe-file-btn--remove:hover {
  color: rgba(239, 68, 68, 1);
  border-color: rgba(239, 68, 68, 0.5);
}

.pe-file-btn--add {
  gap: 6px;
  padding: 8px 12px;
  align-self: flex-start;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
}
</style>
