// client/app/modules/forge/workflows/components/node-editors/IfEditor.tsx
import { Input } from "~/components/ui/input";
import { GitBranch } from "lucide-react";
import type { IfNode } from "../../types/workflow-types";
import type { NodeEditorProps } from "./types";

export function IfEditor({ node, updateNodeData }: NodeEditorProps) {
  const data = node.data as unknown as IfNode;

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-2">
        <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground ml-1">
          Step Name
        </label>
        <Input
          value={data.name || ""}
          onChange={(e) => updateNodeData({ name: e.target.value })}
          placeholder="Name this condition"
          className="bg-accent/10 border-border/50 h-10 font-bold"
        />
      </div>

      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-2 mb-1">
          <GitBranch className="w-3.5 h-3.5 text-violet-500" />
          <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
            Condition Expression
          </label>
        </div>
        <div className="flex items-center gap-2 p-2 text-[10px] bg-violet-500/5 border border-violet-500/10 rounded-lg text-violet-500">
          <span className="font-bold">
            JS expression evaluated against{" "}
            <code className="text-[9px]">trigger</code>,{" "}
            <code className="text-[9px]">steps</code>,{" "}
            <code className="text-[9px]">variables</code>
          </span>
        </div>
        <textarea
          value={data.condition || ""}
          onChange={(e) => updateNodeData({ condition: e.target.value })}
          placeholder={`steps.prevStep.output.status === 200`}
          className="flex min-h-[80px] w-full rounded-lg border border-border/50 bg-background px-3 py-3 text-xs font-mono ring-offset-background placeholder:text-muted-foreground/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 resize-y"
          spellCheck={false}
        />
      </div>

      <div className="flex flex-col gap-2 p-3 rounded-xl bg-accent/5 border border-border/50">
        <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
          Output Branches
        </span>
        <div className="flex gap-3 mt-1">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-emerald-500" />
            <span className="text-xs font-bold text-emerald-500">Then (true)</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-red-500" />
            <span className="text-xs font-bold text-red-500">Else (false)</span>
          </div>
        </div>
        <p className="text-[10px] text-muted-foreground italic leading-relaxed mt-1">
          Connect the green handle (top) for the "true" path and the red handle
          (bottom) for the "false" path.
        </p>
      </div>
    </div>
  );
}

// apps/client/src/features/workflow-editor/components/settings/editors/IfEditor.vue
<template>
  <div class="editor-stack">
    <EditorField label="Step Name">
      <BaseInput
        :model-value="(node.data.name as string) || ''"
        @update:model-value="updateNodeData({ name: $event as string })"
        placeholder="Name this condition"
      />
    </EditorField>

    <EditorField label="Condition Expression" icon="git-branch">
      <div class="editor-hint editor-hint--violet">
        JS expression evaluated against
        <span class="editor-code-snippet">trigger</span>,
        <span class="editor-code-snippet">steps</span>,
        <span class="editor-code-snippet">variables</span>
      </div>
      <ExpressionTextarea
        :model-value="(node.data.condition as string) || ''"
        @update:model-value="updateNodeData({ condition: $event })"
        placeholder="steps.prevStep.output.status === 200"
        spellcheck="false"
      />
    </EditorField>

    <EditorField>
      <div class="editor-branches">
        <span class="editor-field__label">Output Branches</span>
        <div class="branches-legend mt-2">
          <div class="branch-item">
            <div class="branch-dot branch-dot--true"></div>
            <span class="branch-label branch-label--true">Then (true)</span>
          </div>
          <div class="branch-item">
            <div class="branch-dot branch-dot--false"></div>
            <span class="branch-label branch-label--false">Else (false)</span>
          </div>
        </div>
        <p class="editor-hint-text">
          Connect the green handle (top) for the "true" path and the red handle (bottom) for the
          "false" path.
        </p>
      </div>
    </EditorField>
  </div>
</template>

<script setup lang="ts">
import type { NodeEditorProps } from './types'
import EditorField from './EditorField.vue'
import BaseInput from '@/shared/components/base/BaseInput.vue'
import ExpressionTextarea from '../expressions/ExpressionTextarea.vue'

defineProps<NodeEditorProps>()
</script>

<style scoped>
.editor-branches {
  padding: var(--fabric-space-3);
  border-radius: var(--fabric-radius-lg);
  background-color: var(--fabric-bg-surface);
  border: 1px solid var(--fabric-border);
}

.branches-legend {
  display: flex;
  gap: var(--fabric-space-3);
}

.branch-item {
  display: flex;
  align-items: center;
  gap: var(--fabric-space-2);
}

.branch-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
}

.branch-dot--true {
  background-color: rgb(16, 185, 129);
}

.branch-dot--false {
  background-color: rgb(239, 68, 68);
}

.branch-label {
  font-size: var(--fabric-text-xs);
  font-weight: 700;
}

.branch-label--true {
  color: rgb(16, 185, 129);
}

.branch-label--false {
  color: rgb(239, 68, 68);
}

.editor-hint-text {
  font-size: 11px;
  color: var(--fabric-text-muted);
  font-style: italic;
  line-height: 1.5;
  margin-top: var(--fabric-space-2);
}
</style>
