// client/app/modules/forge/workflows/components/RunWorkflowPanel.tsx
import { useState } from "react";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { X, Play, Loader2, Zap } from "lucide-react";
import type { WorkflowItem } from "../types/workflow-types";

interface Props {
  workflow: WorkflowItem;
  onExecute: (params: Record<string, any>) => Promise<void>;
  onClose: () => void;
  loading: boolean;
}

export const RunWorkflowPanel = ({ workflow, onExecute, onClose, loading }: Props) => {
  const [params, setParams] = useState<Record<string, any>>({});
  const schema = workflow.trigger.schema || {};
  const hasParams = Object.keys(schema).length > 0;

  const handleRun = () => {
    onExecute(params);
  };

  return (
    <div className="absolute top-20 right-4 w-[400px] z-[70] bg-card/95 backdrop-blur-xl border border-border shadow-2xl rounded-2xl flex flex-col overflow-hidden animate-in slide-in-from-right-10 duration-300 max-h-[calc(100%-110px)]">
      <div className="flex items-center justify-between p-4 border-b border-border bg-primary/10 shrink-0">
        <div className="flex flex-col">
          <h3 className="font-black text-[9px] uppercase tracking-widest text-primary">Run Configuration</h3>
          <span className="text-sm font-bold truncate max-w-[280px]">Execution Parameters</span>
        </div>
        <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" onClick={onClose}>
          <X className="w-4 h-4" />
        </Button>
      </div>

      <div className="flex-1 overflow-y-auto p-5 custom-scrollbar flex flex-col gap-6">
        <div className="flex flex-col gap-1.5 p-4 rounded-xl bg-primary/5 border border-primary/10">
           <div className="flex items-center gap-2 text-primary">
              <Zap className="w-4 h-4 fill-current" />
              <span className="text-[11px] font-black uppercase tracking-widest">Trigger Info</span>
           </div>
           <p className="text-xs text-muted-foreground leading-relaxed mt-1">
             This workflow starts with a <strong>{workflow.trigger.type}</strong> trigger. 
             {hasParams ? " Below are the required inputs to start execution manually." : " No manual inputs required."}
           </p>
        </div>

        {hasParams && (
          <div className="flex flex-col gap-4">
             <div className="flex items-center gap-2 px-1">
                <div className="w-1.5 h-4 bg-primary rounded-full" />
                <h3 className="text-[11px] font-black text-foreground/70 uppercase tracking-widest">
                  Required Inputs
                </h3>
             </div>

             <div className="flex flex-col gap-4">
               {Object.entries(schema).map(([key, field]: [string, any]) => {
                 const isFile = field.type === "file";
                 return (
                   <div key={key} className="flex flex-col gap-2">
                      <div className="flex justify-between items-center px-1">
                         <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                           {key} {field.required && <span className="text-destructive">*</span>}
                         </label>
                         <span className="text-[9px] bg-accent/30 px-1.5 py-0.5 rounded text-muted-foreground uppercase font-black">
                           {field.type}
                         </span>
                      </div>
                      {isFile ? (
                        <Input 
                          type="file"
                          onChange={(e) => {
                            const file = e.target.files?.[0];
                            if (file) setParams({ ...params, [key]: file });
                          }}
                          className="bg-accent/10 border-border/50 h-10 pt-1.5 font-semibold text-sm cursor-pointer file:bg-primary file:text-primary-foreground file:border-0 file:rounded-md file:px-2 file:py-1 file:text-[10px] file:font-bold file:uppercase file:mr-4 file:hover:bg-primary/80 transition-all"
                        />
                      ) : (
                        <Input 
                          placeholder={`Enter value for ${key}...`}
                          value={params[key] || ""}
                          onChange={(e) => setParams({ ...params, [key]: e.target.value })}
                          className="bg-accent/10 border-border/50 h-10 font-bold text-sm"
                        />
                      )}
                   </div>
                 );
               })}
             </div>
          </div>
        )}
      </div>

      <div className="p-4 border-t border-border bg-accent/10 flex flex-col gap-2 shrink-0">
        <Button 
          variant="default" 
          size="lg" 
          onClick={handleRun}
          disabled={loading}
          className="w-full rounded-2xl h-12 font-semibold text-xs uppercase tracking-[0.08em] shadow-lg shadow-primary/20"
        >
          {loading ? (
            <Loader2 className="w-4 h-4 animate-spin mr-2" />
          ) : (
            <Play className="w-4 h-4 mr-2 fill-current" />
          )}
          {loading ? "Executing..." : "Start Workflow"}
        </Button>
      </div>
    </div>
  );
};

// client-vue/src/features/workflow-editor/components/execution/RunWorkflowPanel.vue
<template>
  <div class="rwp-shell">
    <!-- Header -->
    <div class="rwp-header">
      <div class="rwp-header-info">
        <span class="rwp-title">Run Workflow</span>
        <span class="rwp-subtitle">{{ triggerType }} trigger</span>
      </div>
    </div>

    <!-- Body -->
    <div class="rwp-body">
      <div class="rwp-info-box">
        {{
          hasSchema
            ? 'Fill in the required inputs below to start execution.'
            : 'No inputs required for this workflow. Click Run to execute.'
        }}
      </div>

      <template v-if="hasSchema">
        <p class="rwp-fields-label">Required Inputs</p>
        <div class="rwp-fields">
          <div v-for="(field, key) in schema" :key="key" class="rwp-field">
            <div class="rwp-field-header">
              <label class="rwp-field-label">
                {{ key }}
                <span v-if="field.required" class="rwp-required">*</span>
              </label>
              <span class="rwp-field-type">{{ field.type }}</span>
            </div>
            <input
              v-if="field.type !== 'file'"
              :value="stringParam(key)"
              @input="params[key] = ($event.target as HTMLInputElement).value"
              class="rwp-input"
              :placeholder="`Enter ${key}...`"
            />
            <input
              v-else
              type="file"
              @change="onFileChange(key, $event)"
              class="rwp-input rwp-input--file"
            />
          </div>
        </div>
      </template>
    </div>

    <!-- Footer -->
    <div class="rwp-footer">
      <BaseButton
        variant="primary"
        size="md"
        :full-width="true"
        :loading="executionStore.isExecuting"
        :disabled="executionStore.isExecuting"
        icon-left="play"
        @click="handleRun"
      >
        {{ executionStore.isExecuting ? 'Executing...' : 'Run Workflow' }}
      </BaseButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, computed } from 'vue'
import { useExecutionStore } from '@/features/workflow-editor/stores/execution.store'
import { useAppPanelStore } from '@/shared/stores/app-panel.store'
import BaseButton from '@/shared/components/base/BaseButton.vue'
import type { WorkflowSchemaField } from '@/core/types/workflow.types'

const props = defineProps<{
  workflowId: string
  schema: Record<string, WorkflowSchemaField>
  triggerType: string
}>()

const executionStore = useExecutionStore()
const panelStore = useAppPanelStore()

const params = reactive<Record<string, unknown>>({})
const hasSchema = computed(() => Object.keys(props.schema).length > 0)

/** Safely read a string-typed param value for text/number inputs. */
function stringParam(key: string): string {
  const val = params[key]
  if (typeof val === 'string') return val
  return ''
}

function onFileChange(key: string, event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (file) params[key] = file
}

async function handleRun() {
  try {
    await executionStore.execute(props.workflowId, { ...params })
    panelStore.closePanel()
  } catch {
    // error toast is handled inside execute()
  }
}
</script>

<style scoped>
.rwp-shell {
  display: flex;
  flex-direction: column;
  height: 100%;
}

/* ── Header ───────────────────────────────────────────────── */

.rwp-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--nod8-space-3) var(--nod8-space-4);
  border-bottom: 1px solid var(--nod8-border);
  background-color: var(--nod8-bg-surface);
  flex-shrink: 0;
}

.rwp-header-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.rwp-title {
  font-size: var(--nod8-text-sm);
  font-weight: 600;
  color: var(--nod8-text-primary);
}

.rwp-subtitle {
  font-size: var(--nod8-text-xs);
  color: var(--nod8-text-muted);
  text-transform: capitalize;
}

/* ── Body ─────────────────────────────────────────────────── */

.rwp-body {
  flex: 1;
  overflow-y: auto;
  padding: var(--nod8-space-4);
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-4);
  background-color: var(--nod8-bg-canvas);
}

.rwp-info-box {
  padding: var(--nod8-space-3);
  border-radius: var(--nod8-radius-sm);
  background-color: var(--nod8-bg-elevated);
  border: 1px solid var(--nod8-border);
  font-size: var(--nod8-text-sm);
  color: var(--nod8-text-muted);
  line-height: 1.5;
}

/* ── Fields ───────────────────────────────────────────────── */

.rwp-fields-label {
  font-size: var(--nod8-text-xs);
  font-weight: 600;
  color: var(--nod8-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  margin: 0;
}

.rwp-fields {
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-3);
}

.rwp-field {
  display: flex;
  flex-direction: column;
  gap: var(--nod8-space-1);
}

.rwp-field-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.rwp-field-label {
  font-size: var(--nod8-text-xs);
  font-weight: 500;
  color: var(--nod8-text-primary);
}

.rwp-required {
  color: var(--nod8-red-400);
  margin-left: 2px;
}

.rwp-field-type {
  font-size: var(--nod8-text-xs);
  color: var(--nod8-text-muted);
  background: var(--nod8-bg-elevated);
  padding: 2px 6px;
  border-radius: 4px;
  border: 1px solid var(--nod8-border);
}

/* ── Input ────────────────────────────────────────────────── */

.rwp-input {
  width: 100%;
  height: 36px;
  background-color: var(--nod8-bg-overlay);
  border: 1px solid var(--nod8-border-strong);
  border-radius: var(--nod8-radius-sm);
  padding: 0 var(--nod8-space-3);
  font-size: var(--nod8-text-sm);
  font-family: inherit;
  color: var(--nod8-text-primary);
  outline: none;
  box-sizing: border-box;
  transition: border-color var(--nod8-duration-fast);
}

.rwp-input:focus {
  border-color: var(--nod8-accent);
  box-shadow: 0 0 0 1px var(--nod8-accent);
}

.rwp-input::placeholder {
  color: var(--nod8-text-disabled);
}

.rwp-input--file {
  padding: 6px var(--nod8-space-3);
  height: auto;
  cursor: pointer;
  color: var(--nod8-text-muted);
}

/* ── Footer ───────────────────────────────────────────────── */

.rwp-footer {
  padding: var(--nod8-space-3) var(--nod8-space-4);
  border-top: 1px solid var(--nod8-border);
  background-color: var(--nod8-bg-surface);
  flex-shrink: 0;
}
</style>
