// client/app/modules/nod8/workflows/components/WorkflowEditorDock.tsx
import {
  Play,
  Plus,
  Save,
  X,
  Settings,
  Loader2,
  Activity,
  Download,
  Square,
  ChevronDown,
  Workflow,
  Clock,
  Layers,
  Zap,
  WorkflowIcon,
} from "lucide-react";
import { Button } from "~/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { cn } from "~/lib/utils";
import type { WorkflowItem } from "../types/workflow-types";
import type { DockSection } from "~/shared/components/Nod8Dock";

// ── helpers ──────────────────────────────────────────────────────────────────

function getRelativeTime(iso: string) {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  const h = Math.floor(m / 60);
  const d = Math.floor(h / 24);
  if (d > 0) return `${d}d ago`;
  if (h > 0) return `${h}h ago`;
  if (m > 0) return `${m}m ago`;
  return "Just now";
}

const TRIGGER_ICON: Record<string, React.ElementType> = {
  manual: Play,
  webhook: Zap,
  cron: Clock,
  event: Activity,
};

// ── types ────────────────────────────────────────────────────────────────────

interface Props {
  workflowName: string;
  workflowId: string;
  onRun: () => void;
  onStop: () => void;
  onAddNode: () => void;
  onSave: () => void;
  onSettings: () => void;
  onLogs: () => void;
  onClose: () => void;
  isSaving: boolean;
  isExecuting: boolean;
  isStreaming: boolean;
  isLogsOpen: boolean;
  isDirty: boolean;
  workflow: any;
  /** All available workflows — for the switcher dropdown */
  workflows?: WorkflowItem[];
  /** Called when user switches to another workflow from the dropdown */
  onSwitchWorkflow?: (id: string) => void;
}

export const WorkflowEditorDock = ({
  workflowName,
  workflowId,
  onRun,
  onStop,
  onAddNode,
  onSave,
  onSettings,
  onLogs,
  onClose,
  isSaving,
  isExecuting,
  isStreaming,
  isLogsOpen,
  isDirty,
  workflow,
  workflows = [],
  onSwitchWorkflow,
}: Props) => {
  const isBusy = isExecuting || isStreaming;

  const statusDot = isStreaming
    ? { color: "bg-nod8-editor-dock-status-streaming", animate: true }
    : isDirty
      ? { color: "bg-nod8-editor-dock-status-dirty", animate: false }
      : { color: "bg-nod8-editor-dock-status-idle", animate: false };

  // ── Brand badge with workflow switcher ──
  const brandBadge = (
    <div className="flex items-center gap-2.5 pr-3 border-r border-nod8-dock-section-border h-full">
      <div className="w-7 h-7 flex items-center justify-center rounded-md bg-nod8-dock-badge-bg shrink-0">
        <WorkflowIcon className="w-3.5 h-3.5 text-nod8-dock-badge-icon" />
      </div>

      {/* Workflow name → dropdown to switch */}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            className="flex flex-col justify-center items-start group h-auto py-1 px-2 gap-0.5! rounded-md"
          >
            <div className="flex items-center gap-1">
              <span className="text-sm font-semibold text-nod8-workflow-picker-trigger-title group-hover:text-nod8-workflow-picker-trigger-title-hover transition-colors duration-200 leading-none">
                {workflowName}
              </span>
              <ChevronDown className="w-3 h-3 text-nod8-workflow-picker-trigger-title group-hover:text-nod8-workflow-picker-trigger-title-hover transition-colors shrink-0" />
            </div>
            <div className="flex items-center gap-1.5 mt-0.5">
              <span
                className={cn(
                  "w-1.5 h-1.5 rounded-full",
                  statusDot.color,
                  statusDot.animate && "animate-pulse",
                )}
              />
              <span className="text-xs text-nod8-workflow-picker-trigger-meta leading-none">
                {isStreaming
                  ? "Running"
                  : isDirty
                    ? "Unsaved changes"
                    : workflowId.slice(0, 14)}
              </span>
            </div>
          </Button>
        </DropdownMenuTrigger>

        <DropdownMenuContent
          align="start"
          className="min-w-[320px] bg-nod8-workflow-picker-menu-bg! rounded-none mt-[4px]! p-1.5"
          sideOffset={6}
        >
          <div className="flex flex-col gap-0.5">
            {workflows.map((wf) => {
              const TriggerIcon = TRIGGER_ICON[wf.trigger?.type] ?? Zap;
              const nodeCount = Object.keys(wf.nodes || {}).length;
              const modified = wf.metadata.updatedAt || wf.metadata.createdAt;
              const isCurrent = wf.metadata.id === workflowId;

              return (
                <DropdownMenuItem
                  key={wf.metadata.id}
                  className="group flex items-start gap-3 px-3 py-2.5 rounded-md cursor-pointer focus:bg-nod8-workflow-picker-row-hover-bg"
                  onClick={() => onSwitchWorkflow?.(wf.metadata.id)}
                >
                  <div
                    className={cn(
                      "w-8 h-8 rounded-md border flex items-center justify-center shrink-0 mt-0.5",
                      isCurrent
                        ? "bg-nod8-workflow-picker-icon-tile-active-bg border-nod8-workflow-picker-icon-tile-active-border"
                        : "bg-nod8-workflow-picker-icon-tile-bg border-nod8-workflow-picker-icon-tile-border",
                    )}
                  >
                    <TriggerIcon
                      className={cn(
                        "w-3.5 h-3.5",
                        isCurrent
                          ? "text-nod8-workflow-picker-row-icon-active-text"
                          : "text-nod8-workflow-picker-row-icon-inactive-text",
                      )}
                    />
                  </div>

                  <div className="flex flex-col flex-1 min-w-0 gap-0.5">
                    <div className="flex items-center gap-2">
                      <span
                        className={cn(
                          "text-sm font-medium truncate",
                          isCurrent
                            ? "text-nod8-workflow-picker-row-title"
                            : "text-nod8-workflow-picker-row-subtitle",
                        )}
                      >
                        {wf.metadata.name}
                      </span>
                      <span
                        className={cn(
                          "text-xs px-1.5 py-px rounded border shrink-0",
                          wf.metadata.isActive
                            ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-500"
                            : "bg-amber-500/10 border-amber-500/20 text-amber-500",
                        )}
                      >
                        {wf.metadata.isActive ? "Active" : "Draft"}
                      </span>
                      {isCurrent && (
                        <span className="text-xs px-1.5 py-px rounded border bg-primary/10 border-primary/20 text-primary shrink-0">
                          Open
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <Layers className="w-3 h-3" />
                        {nodeCount} node{nodeCount !== 1 ? "s" : ""}
                      </span>
                      {modified && (
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {getRelativeTime(modified)}
                        </span>
                      )}
                      <span className="font-mono opacity-50 truncate max-w-[100px]">
                        {wf.metadata.id.slice(0, 12)}
                      </span>
                    </div>
                  </div>
                </DropdownMenuItem>
              );
            })}
          </div>

          {workflows.length > 0 && <DropdownMenuSeparator className="my-1" />}

          <DropdownMenuItem
            className="gap-2 text-sm focus:bg-nod8-workflow-picker-menu-item-hover-bg rounded-md cursor-pointer font-medium px-3 py-2 text-nod8-workflow-picker-menu-item-text hover:text-nod8-workflow-picker-menu-item-text-hover"
            onClick={onClose}
          >
            <X className="w-4 h-4" />
            Close workflow
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );

  // ── All action controls live on the right ────────────────────────────────
  const trailing = (
    <div className="flex items-center gap-1">
      {/* Architect tools */}
      <Button
        variant="ghost"
        size="sm"
        onClick={onAddNode}
        disabled={isBusy}
        className="h-7 px-2.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent gap-1.5 text-xs transition-colors disabled:opacity-40"
      >
        <Plus className="w-3 h-3" />
        Add Node
      </Button>
      <Button
        variant="ghost"
        size="icon"
        title="Export JSON"
        onClick={() => {
          const blob = new Blob([JSON.stringify(workflow, null, 2)], {
            type: "application/json",
          });
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `${workflowName.replace(/\s+/g, "_").toLowerCase()}_v${workflow.metadata?.version ?? "1.0"}.json`;
          a.click();
          URL.revokeObjectURL(url);
        }}
        className="h-7 w-7 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
      >
        <Download className="w-3.5 h-3.5" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        onClick={onSettings}
        title="Workflow settings"
        className="h-7 w-7 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
      >
        <Settings className="w-3.5 h-3.5" />
      </Button>

      <div className="h-4 w-px bg-nod8-dock-section-border mx-1" />

      {/* Runtime controls */}
      <Button
        variant="ghost"
        size="sm"
        onClick={onLogs}
        className={`h-7 px-2.5 rounded-md gap-1.5 text-xs transition-colors ${
          isLogsOpen
            ? "bg-accent text-foreground"
            : "text-muted-foreground hover:text-foreground hover:bg-accent"
        }`}
      >
        <Activity className="w-3 h-3" />
        Logs
      </Button>
      {isStreaming ? (
        <Button
          variant="ghost"
          size="sm"
          onClick={onStop}
          className="h-7 px-2.5 rounded-md text-red-400 hover:text-red-500 hover:bg-red-500/10 gap-1.5 text-xs transition-colors"
        >
          <Square className="w-3 h-3 fill-current" />
          Stop
        </Button>
      ) : (
        <Button
          variant="ghost"
          size="sm"
          onClick={onRun}
          disabled={isExecuting}
          className="h-7 px-2.5 rounded-md text-muted-foreground hover:text-emerald-500 hover:bg-emerald-500/10 gap-1.5 text-xs transition-colors"
        >
          {isExecuting ? (
            <Loader2 className="w-3 h-3 animate-spin" />
          ) : (
            <Play className="w-3 h-3 fill-current" />
          )}
          Run
        </Button>
      )}

      <div className="h-4 w-px bg-nod8-dock-section-border mx-1" />

      {/* Save CTA */}
      <Button
        onClick={onSave}
        disabled={isSaving || !isDirty || isBusy}
        size="sm"
        variant={isDirty && !isBusy ? "emphasis" : "ghost"}
        className="h-7 px-3 text-xs font-medium gap-1.5 rounded-md disabled:opacity-40 transition-colors"
      >
        {isSaving ? (
          <Loader2 className="w-3 h-3 animate-spin" />
        ) : (
          <Save className="w-3 h-3" />
        )}
        {isSaving ? "Saving" : "Save"}
      </Button>

      <div className="h-4 w-px bg-nod8-dock-section-border mx-1" />

      {/* Close */}
      <Button
        variant="ghost"
        size="icon-lg"
        onClick={onClose}
        title="Close editor"
        className="h-7 w-7 rounded-md text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors"
      >
        <X className="w-3.5 h-3.5" />
      </Button>
    </div>
  );

  // Render a customized dock — brand badge on the left, all actions on the right
  return (
    <div className="nod8-dock nod8-dock--editor h-12 w-full flex items-center bg-nod8-dock-bg border-b border-nod8-dock-border shrink-0 px-3 gap-2">
      {brandBadge}
      <div className="flex-1" />
      <div className="flex items-center">{trailing}</div>
    </div>
  );
};

// client-vue/src/features/workflow-editor/components/ui/WorkflowEditorDock.vue
<template>
  <AppDock>
    <!-- ── Left: Brand badge + Workflow name + status ── -->
    <template #left>
      <div class="wed-brand">
        <!-- Icon tile -->
        <div class="wed-brand__icon">
          <LucideIcon name="workflow" :size="14" />
        </div>

        <!-- Name + status row -->
        <div class="wed-brand__meta">
          <!-- Workflow name → opens dropdown -->
          <AppDropdownMenu position="bottom-start" :offset="3">
            <template #trigger>
              <div class="flex flex-col gap-1">
                <div class="wed-name-wrap">
                  <span class="wed-name">{{ workflowName }}</span>
                  <LucideIcon name="chevron-down" :size="12" class="wed-name__chevron" />
                </div>

                <!-- Status / ID sub-row -->
                <div class="wed-status-row">
                  <span
                    class="wed-status-dot"
                    :class="{
                      'wed-status-dot--streaming': isStreaming,
                      'wed-status-dot--dirty': isDirty && !isStreaming,
                    }"
                  />
                  <span class="wed-status-text">
                    <template v-if="isStreaming">Running</template>
                    <template v-else-if="isDirty">Unsaved Changes</template>
                    <template v-else>{{ workflowId?.slice(0, 14) || 'New Workflow' }}</template>
                  </span>
                </div>
              </div>
            </template>

            <!-- Search -->
            <div class="dock-search" :style="{ padding: 0 }">
              <BaseInput
                v-model="searchQuery"
                icon-left="search"
                placeholder="Search workflows…"
                @click.stop
              />
            </div>

            <AppDropdownDivider />

            <AppDropdownItem icon="cloud-upload" label="Import from JSON" @click="handleImport" />
            <AppDropdownItem
              icon="plus-circle"
              label="Create Workflow"
              :disabled="isCreating"
              @click="handleCreate"
            />
            
            <AppDropdownItem icon="download" :danger="false" @click="$emit('export-workflow')">
              Export workflow
            </AppDropdownItem>

            <template v-if="filteredWorkflows.length > 0">
              <AppDropdownDivider />

              <div style="max-height: 350px; overflow-y: auto;">
                <template v-for="w in filteredWorkflows" :key="w.metadata.id">
                  <AppDropdownItem
                  icon="workflow"
                  :label="w.metadata.name"
                  @click="handleOpenWorkflow(w)"
                >
                  <template #element>
                    <div class="dropdown-item-container">
                      <div class="dic-row">
                        <span class="text-xs text-muted font-mono tracking-tight text-truncate">
                          {{ w.metadata.id.slice(0, 13) }}…
                        </span>
                        <span class="text-xs text-muted font-mono tracking-tight">
                          {{
                            (() => {
                              const nodes = Object.keys(w.nodes).length
                              return nodes === 1 ? `${nodes} Node` : `${nodes} Nodes`
                            })()
                          }}
                        </span>
                      </div>
                      <div class="dic-row" style="margin-top: 4px;">
                        <span
                          class="workflow-badge"
                          :class="{
                            'workflow-badge--draft': w.metadata.isDraft,
                            'workflow-badge--published': !w.metadata.isDraft && w.metadata.isActive,
                            'workflow-badge--inactive': !w.metadata.isDraft && !w.metadata.isActive,
                          }"
                        >
                          {{ w.metadata.isDraft ? 'Draft' : w.metadata.isActive ? 'Published' : 'Inactive' }}
                        </span>
                        <span v-if="w.metadata.publishedAt" class="text-xs text-muted" style="font-size: 10px;">
                          {{ getRelativeTime(new Date(w.metadata.publishedAt).getTime()) }}
                        </span>
                      </div>
                    </div>
                  </template>
                </AppDropdownItem>
                </template>
              </div>
            </template>

            <template v-else-if="searchQuery">
              <AppDropdownDivider />
              <div class="dock-empty">No workflows match "{{ searchQuery }}"</div>
            </template>
          </AppDropdownMenu>
        </div>
      </div>

      <!-- Section divider -->
      <div class="wed-divider-v" />
    </template>

    <!-- ── Right: All action buttons ── -->
    <template #right>
      <!-- Add Node -->
      <BaseButton
        size="sm"
        variant="ghost"
        icon-left="plus"
        :disabled="isBusy"
        @click="$emit('add-node')"
      >
        Add Node
      </BaseButton>

      <!-- Settings -->
      <BaseButton
        size="sm"
        variant="ghost"
        icon-left="settings"
        :disabled="isBusy"
        title="Workflow settings"
        @click="$emit('settings')"
      />

      <div class="wed-divider-v" />

      <!-- Logs -->
      <BaseButton
        size="sm"
        variant="ghost"
        icon-left="scroll-text"
        :class="{ 'wed-btn--active': isLogsOpen }"
        @click="$emit('toggle-logs')"
      >
        Logs
      </BaseButton>

      <!-- Stop (shown while streaming) -->
      <BaseButton
        v-if="isStreaming"
        size="sm"
        variant="danger"
        icon-left="square"
        @click="$emit('stop')"
      >
        Stop
      </BaseButton>

      <!-- Run -->
      <BaseButton
        v-else
        size="sm"
        variant="ghost"
        :disabled="isExecuting"
        :loading="isExecuting"
        icon-left="play"
        class="wed-btn--run"
        @click="$emit('run')"
      >
        Run
      </BaseButton>

      <div class="wed-divider-v" />

      <!-- Save -->
      <BaseButton
        size="sm"
        :variant="isDirty ? 'primary' : 'ghost'"
        :disabled="isSaving || !isDirty || isBusy"
        :loading="isSaving"
        icon-left="save"
        @click="$emit('save')"
      >
        {{ isSaving ? 'Saving…' : 'Save' }}
      </BaseButton>

      <div class="wed-divider-v" />

      <!-- Publish/Unpublish -->
      <WorkflowPublishButton
        v-if="workflow"
        :workflow="workflow"
        @updated="$emit('workflow-updated', $event)"
      />

      <!-- Close -->
      <BaseButton
        size="sm"
        variant="ghost"
        icon-left="x"
        title="Close editor"
        class="wed-btn--close"
        @click="$emit('close')"
      />
    </template>
  </AppDock>
</template>

<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import AppDock from '@/shared/components/layout/AppDock.vue'
import BaseButton from '@/shared/components/base/BaseButton.vue'
import BaseInput from '@/shared/components/base/BaseInput.vue'
import LucideIcon from '@/shared/icons/LucideIcon.vue'
import AppDropdownMenu from '@/shared/components/overlay/Dropdown/AppDropdownMenu.vue'
import AppDropdownItem from '@/shared/components/overlay/Dropdown/AppDropdownItem.vue'
import AppDropdownDivider from '@/shared/components/overlay/Dropdown/AppDropdownDivider.vue'
import WorkflowPublishButton from './WorkflowPublishButton.vue'
import type { WorkflowItem } from '@/core/types/workflow.types'
import { workflowsApi } from '@/core/api/workflows.api'
import { useApi } from '@/shared/composables/useApi'
import { useWorkflowActions } from '@/features/workflow-editor/composables/useWorkflowActions'

// ── Props ─────────────────────────────────────────────────────────────────

const props = defineProps<{
  workflowName: string
  workflowId: string
  workflow?: WorkflowItem
  isSaving?: boolean
  isExecuting?: boolean
  isStreaming?: boolean
  isLogsOpen?: boolean
  isDirty?: boolean
}>()

// ── Emits ─────────────────────────────────────────────────────────────────

defineEmits<{
  (e: 'run'): void
  (e: 'stop'): void
  (e: 'add-node'): void
  (e: 'save'): void
  (e: 'settings'): void
  (e: 'toggle-logs'): void
  (e: 'close'): void
  (e: 'export-workflow'): void
  (e: 'workflow-updated', workflow: WorkflowItem): void
}>()

// ── Derived ───────────────────────────────────────────────────────────────

const isBusy = computed(() => props.isExecuting || props.isStreaming)

// ── Dropdown Logic ────────────────────────────────────────────────────────

const { openWorkflow } = useWorkflowActions()

const {
  data: workflowsList,
  execute: fetchWorkflows,
} = useApi(workflowsApi.getAll, [])

onMounted(() => {
  fetchWorkflows().catch(console.error)
})

const searchQuery = ref('')

const filteredWorkflows = computed(() => {
  const list = workflowsList.value ?? []
  const q = searchQuery.value.trim().toLowerCase()
  if (!q) return list
  return list.filter((w) => w.metadata.name.toLowerCase().includes(q))
})

const { execute: createWorkflowApi, loading: isCreating } = useApi(workflowsApi.create)

async function handleCreate() {
  const newWorkflow: WorkflowItem = {
    metadata: {
      id: crypto.randomUUID(),
      name: 'New Workflow',
      version: '1',
      isActive: false,
      isDraft: true,
      public: false,
      createdAt: new Date().toISOString(),
    },
    trigger: { type: 'manual' },
    nodes: {},
    edges: [],
  }

  try {
    const created = await createWorkflowApi(newWorkflow)
    await fetchWorkflows()
    openWorkflow(created)
  } catch (e) {
    console.error('Failed to create workflow', e)
  }
}

function handleImport() {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = '.json,application/json'
  input.onchange = async (e) => {
    const file = (e.target as HTMLInputElement).files?.[0]
    if (!file) return
    try {
      const text = await file.text()
      const workflow: WorkflowItem = JSON.parse(text)
      workflow.metadata.id = crypto.randomUUID()
      workflow.metadata.createdAt = new Date().toISOString()
      workflow.metadata.isDraft = true
      const created = await createWorkflowApi(workflow)
      await fetchWorkflows()
      openWorkflow(created)
    } catch (e) {
      console.error('Failed to import workflow', e)
    }
  }
  input.click()
}

function handleOpenWorkflow(w: WorkflowItem) {
  openWorkflow(w)
}

function getRelativeTime(ms: number): string {
  const diff = Date.now() - ms
  const m = Math.floor(diff / 60_000)
  const h = Math.floor(m / 60)
  const d = Math.floor(h / 24)
  if (d > 0) return `${d}d ago`
  if (h > 0) return `${h}h ago`
  if (m > 0) return `${m}m ago`
  return 'Just now'
}
</script>
